/**
 * Fallback when word-packs.json cannot load (e.g. file://). Mirrors word-packs.json.
 */
window.WORD_PACKS_BUILTIN = [
  {
    "category": "Everyday objects",
    "words": [
      "umbrella",
      "toothbrush",
      "backpack",
      "lamp",
      "mirror",
      "pillow",
      "wallet",
      "headphones",
      "charger",
      "keys",
      "watch",
      "sunglasses",
      "notebook",
      "pen",
      "water bottle",
      "tissue box",
      "remote",
      "blanket",
      "hanger",
      "soap",
      "thermos",
      "coaster",
      "doorbell",
      "laundry basket",
      "cutting board",
      "phone case",
      "tripod",
      "sticky notes",
      "lint roller",
      "shoe rack",
      "mouse pad",
      "desk organizer",
      "paper towel",
      "dish sponge",
      "measuring cup",
      "salt shaker",
      "pepper grinder",
      "reusable bag",
      "desk lamp",
      "alarm keypad",
      "calendar magnet",
      "coin jar",
      "shoehorn",
      "laundry clip",
      "pencil holder",
      "window blinds",
      "oven mitt",
      "bath mat",
      "mailbox key",
      "charging cable"
    ]
  },
  {
    "category": "Food & drink",
    "words": [
      "pizza",
      "sushi",
      "coffee",
      "popcorn",
      "avocado",
      "croissant",
      "smoothie",
      "noodles",
      "burger",
      "tacos",
      "ice cream",
      "ramen",
      "bagel",
      "matcha",
      "bubble tea",
      "steak",
      "salad",
      "pancakes",
      "hot dog",
      "fries",
      "dumplings",
      "burrito",
      "lasagna",
      "mojito",
      "apple pie",
      "cheesecake",
      "falafel",
      "fried rice",
      "paella",
      "risotto",
      "spring rolls",
      "milkshake",
      "waffles",
      "omelette",
      "nachos",
      "fajitas",
      "chili",
      "cupcake",
      "brownie",
      "donut",
      "macarons",
      "sorbet",
      "lemonade",
      "iced tea",
      "hot chocolate",
      "grilled cheese",
      "samosa",
      "gnocchi",
      "bibimbap",
      "shawarma"
    ]
  },
  {
    "category": "Places",
    "words": [
      "library",
      "airport",
      "beach",
      "gym",
      "museum",
      "campground",
      "bakery",
      "theater",
      "zoo",
      "mall",
      "hospital",
      "school",
      "park",
      "restaurant",
      "hotel",
      "subway station",
      "church",
      "stadium",
      "spa",
      "arcade",
      "aquarium",
      "castle",
      "bridge",
      "farm",
      "courthouse",
      "bookstore",
      "pharmacy",
      "observatory",
      "harbor",
      "planetarium",
      "train depot",
      "city hall",
      "bus stop",
      "skyscraper",
      "town square",
      "fountain",
      "playground",
      "concert hall",
      "art gallery",
      "bank",
      "post office",
      "pier",
      "market",
      "factory",
      "embassy",
      "neighborhood",
      "parking garage",
      "downtown",
      "waterpark",
      "campus quad"
    ]
  },
  {
    "category": "Animals",
    "words": [
      "penguin",
      "octopus",
      "flamingo",
      "raccoon",
      "hedgehog",
      "dolphin",
      "sloth",
      "owl",
      "elephant",
      "tiger",
      "giraffe",
      "koala",
      "panda",
      "wolf",
      "fox",
      "eagle",
      "shark",
      "turtle",
      "rabbit",
      "horse",
      "crocodile",
      "kangaroo",
      "cheetah",
      "peacock",
      "moose",
      "otter",
      "chameleon",
      "buffalo",
      "lemur",
      "walrus",
      "meerkat",
      "armadillo",
      "gorilla",
      "hippopotamus",
      "rhinoceros",
      "zebra",
      "deer",
      "beaver",
      "alligator",
      "lobster",
      "seahorse",
      "starfish",
      "jellyfish",
      "parrot",
      "falcon",
      "swan",
      "goat",
      "donkey",
      "hamster",
      "llama"
    ]
  },
  {
    "category": "Christmas",
    "words": [
      "Santa",
      "reindeer",
      "snowman",
      "ornament",
      "wreath",
      "mistletoe",
      "gingerbread",
      "eggnog",
      "stocking",
      "elf",
      "sleigh",
      "carol",
      "nutcracker",
      "candy cane",
      "fireplace",
      "advent calendar",
      "tinsel",
      "holly",
      "North Pole",
      "gift wrap",
      "snow globe",
      "chimney",
      "hot cocoa",
      "tree topper",
      "Christmas lights",
      "gingerbread house",
      "peppermint bark",
      "wrapped present",
      "snowflake",
      "holiday card",
      "fruitcake",
      "ice skates",
      "advent wreath",
      "toy train",
      "gift tag",
      "cookie platter",
      "frosting",
      "winter scarf",
      "holiday sweater",
      "pine tree",
      "bells",
      "jingle",
      "holiday parade",
      "chimney smoke",
      "snow angel",
      "sled hill",
      "winter village",
      "gift ribbon",
      "caroling group",
      "wrapped toy"
    ]
  },
  {
    "category": "Objects",
    "words": [
      "hammer",
      "scissors",
      "tape",
      "glue",
      "stapler",
      "calendar",
      "alarm clock",
      "umbrella stand",
      "vacuum",
      "broom",
      "flashlight",
      "battery",
      "extension cord",
      "picture frame",
      "vase",
      "candle",
      "clock",
      "rug",
      "curtain",
      "bookshelf",
      "clipboard",
      "paperclip",
      "binder",
      "spray bottle",
      "laundry detergent",
      "power bank",
      "notepad",
      "tote bag",
      "zip tie",
      "magnifying glass",
      "air freshener",
      "bookmark",
      "clipboard stand",
      "folder",
      "ruler",
      "eraser",
      "paintbrush",
      "dustpan",
      "plunger",
      "bucket",
      "door stopper",
      "safety pin",
      "needle",
      "thread spool",
      "storage box",
      "label maker",
      "watering can",
      "coathook",
      "nightlight",
      "keychain"
    ]
  },
  {
    "category": "Movies & TV",
    "words": [
      "Breaking Bad",
      "The Office",
      "Friends",
      "Game of Thrones",
      "Stranger Things",
      "The Simpsons",
      "Titanic",
      "Avatar",
      "Star Wars",
      "Harry Potter",
      "The Godfather",
      "The Dark Knight",
      "Inception",
      "Black Panther",
      "Spider-Man",
      "The Matrix",
      "Squid Game",
      "Wednesday",
      "The Crown",
      "Ted Lasso",
      "The Mandalorian",
      "Succession",
      "The Last of Us",
      "Barbie",
      "Oppenheimer",
      "Frozen",
      "Shrek",
      "Toy Story",
      "The Avengers",
      "Lord of the Rings",
      "Sherlock",
      "Black Mirror",
      "Interstellar",
      "The Batman",
      "The Lion King",
      "Gladiator",
      "The Walking Dead",
      "How I Met Your Mother",
      "Peaky Blinders",
      "The Witcher",
      "The Prestige",
      "Severance",
      "The Bear",
      "Arcane",
      "The Shawshank Redemption",
      "Forrest Gump",
      "The Social Network",
      "Dune",
      "The Boys",
      "House of the Dragon"
    ]
  },
  {
    "category": "Music",
    "words": [
      "The Beatles",
      "Frank Sinatra",
      "Elvis Presley",
      "Michael Jackson",
      "Madonna",
      "Queen",
      "David Bowie",
      "Prince",
      "Whitney Houston",
      "Stevie Wonder",
      "Elton John",
      "Taylor Swift",
      "Drake",
      "Kanye West",
      "Beyoncé",
      "Rihanna",
      "Ariana Grande",
      "Billie Eilish",
      "The Weeknd",
      "Travis Scott",
      "Kendrick Lamar",
      "Eminem",
      "Jay-Z",
      "Bad Bunny",
      "Central Cee",
      "Polo G",
      "SZA",
      "Doja Cat",
      "Harry Styles",
      "Olivia Rodrigo",
      "BTS",
      "BLACKPINK",
      "Nirvana",
      "Metallica",
      "AC/DC",
      "Coldplay",
      "Radiohead",
      "Adele",
      "Ed Sheeran",
      "Celine Dion",
      "Juice WRLD",
      "NF",
      "Lil Skies",
      "XXXTentacion",
      "The Kid LAROI",
      "KSI",
      "Lil Uzi Vert",
      "Lil Tecca",
      "Chief Keef",
      "YNW Melly",
      "Lil Mosey",
      "A Boogie wit da Hoodie",
      "Snoop Dogg",
      "50 Cent",
      "DaBaby",
      "Gunna",
      "Lil Baby",
      "Lil Drake",
      "G-Eazy",
      "J. Cole",
      "21 Savage",
      "Future",
      "Metro Boomin",
      "Pi'erre Bourne",
      "Tee Grizzley",
      "N.W.A.",
      "BROCKHAMPTON",
      "Mobb Deep",
      "OutKast",
      "Kodak Black",
      "JID",
      "Roddy Ricch",
      "Tyler, The Creator",
      "Kali Uchis",
      "Sheck Wes",
      "ScHoolboy Q",
      "Dr. Dre",
      "DMX",
      "Nas",
      "Lil Nas X",
      "Chance the Rapper",
      "King Von",
      "Don Toliver",
      "A$AP Rocky",
      "Mac Miller",
      "Lil Wayne",
      "Trippie Redd",
      "Pop Smoke",
      "Playboi Carti",
      "Kid Cudi",
      "Pusha T",
      "John Legend",
      "AJR",
      "Freddie Gibbs",
      "Justin Bieber",
      "Young Thug",
      "Childish Gambino",
      "Rick Ross",
      "Big Sean",
      "2 Chainz",
      "2Pac",
      "The Notorious B.I.G.",
      "Mos Def",
      "Denzel Curry",
      "Lil Yachty",
      "T-Pain",
      "Baby Keem",
      "Daft Punk",
      "Bruno Mars",
      "Carly Rae Jepsen",
      "Maroon 5",
      "Imagine Dragons",
      "Dax",
      "Katy Perry",
      "Macklemore",
      "Bastille",
      "OneRepublic",
      "Flo Rida",
      "Black Eyed Peas",
      "The Chainsmokers",
      "5 Seconds of Summer",
      "Miley Cyrus",
      "Usher",
      "Pitbull",
      "Wiz Khalifa",
      "Charlie Puth",
      "Selena Gomez",
      "Pharrell Williams",
      "Panic! At the Disco",
      "Avicii",
      "Sombr",
      "Gorillaz",
      "bbno$",
      "Teddy Swims",
      "JVKE",
      "d4vd",
      "Shaboozey",
      "Post Malone",
      "Twenty One Pilots",
      "The Strokes",
      "Sia",
      "Lin-Manuel Miranda",
      "Lana Del Rey",
      "Arctic Monkeys",
      "Ty Dolla $ign",
      "Alicia Keys"
    ]
  },
  {
    "category": "Locations",
    "words": [
      "Times Square",
      "Eiffel Tower",
      "Grand Canyon",
      "Big Ben",
      "Great Wall",
      "Machu Picchu",
      "Sydney Opera House",
      "Niagara Falls",
      "Hollywood",
      "Central Park",
      "Stonehenge",
      "Colosseum",
      "Taj Mahal",
      "Mount Everest",
      "Sahara Desert",
      "Amazon Rainforest",
      "Venice canals",
      "Las Vegas Strip",
      "Golden Gate Bridge",
      "Statue of Liberty",
      "Burj Khalifa",
      "Mount Fuji",
      "Santorini",
      "Iguazu Falls",
      "Petra",
      "Banff",
      "Yosemite",
      "Angkor Wat",
      "Serengeti",
      "Uluru",
      "Jeju Island",
      "Cinque Terre",
      "Great Barrier Reef",
      "Table Mountain",
      "Victoria Falls",
      "Mount Kilimanjaro",
      "Salar de Uyuni",
      "Death Valley",
      "Blue Lagoon",
      "Galapagos Islands",
      "Antelope Canyon",
      "Patagonia",
      "Cappadocia",
      "Matterhorn",
      "Lake Como",
      "Amalfi Coast",
      "Bora Bora",
      "Swiss Alps",
      "Svalbard",
      "Iceland Ring Road"
    ]
  },
  {
    "category": "Sports",
    "words": [
      "basketball",
      "soccer",
      "tennis",
      "baseball",
      "football",
      "volleyball",
      "golf",
      "swimming",
      "boxing",
      "skiing",
      "surfing",
      "hockey",
      "cricket",
      "rugby",
      "badminton",
      "wrestling",
      "cycling",
      "marathon",
      "skateboarding",
      "gymnastics",
      "table tennis",
      "fencing",
      "archery",
      "rowing",
      "karate",
      "snowboarding",
      "triathlon",
      "motocross",
      "handball",
      "water polo",
      "bobsled",
      "pole vault",
      "judo",
      "taekwondo",
      "sumo",
      "dodgeball",
      "lacrosse",
      "curling",
      "canoeing",
      "sailing",
      "skating",
      "high jump",
      "long jump",
      "shot put",
      "discus",
      "weightlifting",
      "equestrian",
      "climbing",
      "snooker",
      "eSports"
    ]
  },
  {
    "category": "Professions",
    "words": [
      "doctor",
      "nurse",
      "teacher",
      "engineer",
      "lawyer",
      "chef",
      "pilot",
      "firefighter",
      "police officer",
      "scientist",
      "artist",
      "musician",
      "writer",
      "architect",
      "dentist",
      "veterinarian",
      "electrician",
      "plumber",
      "journalist",
      "accountant",
      "pharmacist",
      "paramedic",
      "mechanic",
      "barber",
      "software developer",
      "data analyst",
      "real estate agent",
      "flight attendant",
      "product manager",
      "biologist",
      "translator",
      "UX designer",
      "web designer",
      "civil engineer",
      "psychologist",
      "economist",
      "librarian",
      "astronomer",
      "meteorologist",
      "social worker",
      "therapist",
      "photographer",
      "videographer",
      "sound engineer",
      "athletic trainer",
      "nutritionist",
      "security guard",
      "dispatcher",
      "entrepreneur",
      "project coordinator"
    ]
  },
  {
    "category": "Brands",
    "words": [
      "Nike",
      "Apple",
      "Google",
      "Amazon",
      "Starbucks",
      "McDonald's",
      "Coca-Cola",
      "Disney",
      "Samsung",
      "Sony",
      "Adidas",
      "IKEA",
      "Netflix",
      "Spotify",
      "Lego",
      "Toyota",
      "BMW",
      "Gucci",
      "Prada",
      "Nintendo",
      "Puma",
      "Tesla",
      "Rolex",
      "PlayStation",
      "Xbox",
      "Uber",
      "Airbnb",
      "TikTok",
      "Red Bull",
      "Pepsi",
      "Huawei",
      "Dell",
      "Lenovo",
      "HP",
      "Asus",
      "Intel",
      "AMD",
      "Visa",
      "Mastercard",
      "Shell",
      "Ikea",
      "Canon",
      "Nikon",
      "Twitch",
      "Discord",
      "Fanta",
      "Sprite",
      "Subway",
      "Domino's",
      "KFC"
    ]
  },
  {
    "category": "Tools",
    "words": [
      "screwdriver",
      "wrench",
      "pliers",
      "drill",
      "saw",
      "measuring tape",
      "level",
      "chisel",
      "sandpaper",
      "ladder",
      "wheelbarrow",
      "shovel",
      "rake",
      "pickaxe",
      "clamp",
      "file",
      "hex key",
      "socket",
      "mallet",
      "multimeter",
      "soldering iron",
      "utility knife",
      "bolt cutter",
      "caulking gun",
      "paint roller",
      "vice grip",
      "stud finder",
      "torque wrench",
      "pipe cutter",
      "wire stripper",
      "crowbar",
      "nail gun",
      "heat gun",
      "sledgehammer",
      "trowel",
      "pry bar",
      "bolt driver",
      "tap wrench",
      "awl",
      "hacksaw",
      "miter box",
      "hand plane",
      "workbench",
      "toolbox",
      "safety goggles",
      "work gloves",
      "extension ladder",
      "shop vacuum",
      "caliper"
    ]
  },
  {
    "category": "Vehicles",
    "words": [
      "bicycle",
      "motorcycle",
      "scooter",
      "suv",
      "pickup truck",
      "convertible",
      "ambulance",
      "fire truck",
      "tractor",
      "bulldozer",
      "forklift",
      "subway",
      "helicopter",
      "speedboat",
      "cruise ship",
      "jet ski",
      "skateboard",
      "roller skates",
      "golf cart",
      "camper van",
      "minivan",
      "limousine",
      "tram",
      "ferry",
      "hot air balloon",
      "cargo plane",
      "race car",
      "snowmobile",
      "rickshaw",
      "monorail",
      "tow truck",
      "kayak",
      "canoe",
      "submarine",
      "airship",
      "glider",
      "bullet train",
      "freight train",
      "diesel truck",
      "police car",
      "taxi",
      "school bus",
      "garbage truck",
      "cement mixer",
      "food truck",
      "ATV",
      "dirt bike",
      "segway",
      "longboard",
      "paraglider"
    ]
  },
  {
    "category": "Superpowers",
    "words": [
      "flight",
      "invisibility",
      "teleportation",
      "super strength",
      "mind reading",
      "time travel",
      "laser eyes",
      "healing",
      "shape-shifting",
      "telekinesis",
      "super speed",
      "force field",
      "weather control",
      "duplication",
      "talking to animals",
      "phasing through walls",
      "elastic body",
      "ice powers",
      "fire powers",
      "electricity powers",
      "x-ray vision",
      "sonic scream",
      "gravity control",
      "invulnerability",
      "metal manipulation",
      "size changing",
      "energy blast",
      "portal creation",
      "clairvoyance",
      "sound manipulation",
      "plant control",
      "light bending",
      "memory erasure",
      "mind control",
      "precognition",
      "enhanced senses",
      "night vision",
      "water breathing",
      "earth control",
      "fire immunity",
      "shadow travel",
      "luck manipulation",
      "dream walking",
      "spirit summoning",
      "magnetism",
      "blood control",
      "telepathy",
      "emotion control",
      "phoenix rebirth",
      "storm summoning"
    ]
  },
  {
    "category": "Fears",
    "words": [
      "heights",
      "spiders",
      "snakes",
      "public speaking",
      "darkness",
      "thunder",
      "needles",
      "flying",
      "deep water",
      "tight spaces",
      "clowns",
      "dentist",
      "ghosts",
      "failure",
      "rejection",
      "loneliness",
      "crowds",
      "germs",
      "dogs",
      "bees",
      "elevators",
      "storms",
      "small talk",
      "being late",
      "open ocean",
      "roller coasters",
      "conflict",
      "mirrors at night",
      "abandonment",
      "silence",
      "thunderstorms",
      "lost phone",
      "deep caves",
      "nightmares",
      "rats",
      "birds",
      "helicopters",
      "bridges",
      "hospitals",
      "school tests",
      "stage fright",
      "driving",
      "getting lost",
      "power outage",
      "sleep paralysis",
      "basements",
      "social media",
      "loud noises",
      "shadows",
      "thunderclaps"
    ]
  },
  {
    "category": "Inventions",
    "words": [
      "light bulb",
      "telephone",
      "airplane",
      "internet",
      "printing press",
      "camera",
      "refrigerator",
      "microwave",
      "GPS",
      "antibiotics",
      "vaccine",
      "steam engine",
      "wheel",
      "compass",
      "gunpowder",
      "paper",
      "glasses",
      "battery",
      "semiconductor",
      "3D printer",
      "transistor",
      "satellite",
      "smartphone",
      "calculator",
      "bar code",
      "sewing machine",
      "wind turbine",
      "touchscreen",
      "laser",
      "pacemaker",
      "GPS navigation",
      "robotic arm",
      "solar panel",
      "battery charger",
      "electric motor",
      "fiber optics",
      "x-ray machine",
      "MRI scanner",
      "ultrasound",
      "water filter",
      "vaccination needle",
      "ink pen",
      "zipper",
      "stethoscope",
      "elevator",
      "air conditioner",
      "dishwasher",
      "washing machine",
      "flash drive",
      "drone"
    ]
  },
  {
    "category": "Celebrities",
    "words": [
      "Tom Hanks",
      "Dwayne Johnson",
      "Jennifer Lawrence",
      "Leonardo DiCaprio",
      "Zendaya",
      "Will Smith",
      "Meryl Streep",
      "Robert Downey Jr.",
      "Margot Robbie",
      "Ryan Reynolds",
      "Emma Stone",
      "Chris Hemsworth",
      "Scarlett Johansson",
      "Keanu Reeves",
      "Timothée Chalamet",
      "Lady Gaga",
      "Denzel Washington",
      "Sandra Bullock",
      "Jackie Chan",
      "Morgan Freeman",
      "Chris Evans",
      "Gal Gadot",
      "Pedro Pascal",
      "Anya Taylor-Joy",
      "Jenna Ortega",
      "Cillian Murphy",
      "Florence Pugh",
      "Michael B. Jordan",
      "Sydney Sweeney",
      "Dev Patel",
      "Paul Rudd",
      "Lupita Nyong'o",
      "Anne Hathaway",
      "Natalie Portman",
      "Hugh Jackman",
      "Chris Pratt",
      "Tom Holland",
      "Benedict Cumberbatch",
      "Millie Bobby Brown",
      "Henry Cavill",
      "Viola Davis",
      "Pedro Almodovar",
      "Priyanka Chopra",
      "Rami Malek",
      "Daniel Kaluuya",
      "Jennifer Aniston",
      "Julia Roberts",
      "Ben Affleck",
      "Kristen Bell",
      "Mads Mikkelsen"
    ]
  },
  {
    "category": "Games",
    "words": [
      "Monopoly",
      "Chess",
      "Uno",
      "Scrabble",
      "Clue",
      "Risk",
      "Jenga",
      "Poker",
      "Minecraft",
      "Fortnite",
      "Mario Kart",
      "The Sims",
      "Among Us",
      "Roblox",
      "Call of Duty",
      "FIFA",
      "Pokémon",
      "Zelda",
      "Halo",
      "Grand Theft Auto",
      "Valorant",
      "Apex Legends",
      "Rocket League",
      "Animal Crossing",
      "Elden Ring",
      "Overwatch",
      "Street Fighter",
      "Counter-Strike",
      "League of Legends",
      "God of War",
      "Metal Gear Solid",
      "Portal 2",
      "Skyrim",
      "The Legend of Zelda: Breath of the Wild",
      "The Last of Us Part II",
      "Red Dead Redemption 2",
      "Hollow Knight",
      "Celeste",
      "Terraria",
      "Dota 2",
      "PUBG",
      "Rainbow Six Siege",
      "Destiny 2",
      "Mass Effect",
      "Persona 5",
      "Final Fantasy VII",
      "Dark Souls",
      "Resident Evil",
      "Silent Hill",
      "Tekken"
    ]
  },
  {
    "category": "Anime",
    "words": [
      "Naruto",
      "Dragon Ball",
      "One Piece",
      "Attack on Titan",
      "Demon Slayer",
      "My Hero Academia",
      "Death Note",
      "Fullmetal Alchemist",
      "Sailor Moon",
      "Spirited Away",
      "Cowboy Bebop",
      "Jujutsu Kaisen",
      "Hunter x Hunter",
      "Bleach",
      "Studio Ghibli",
      "Pokémon anime",
      "One Punch Man",
      "Tokyo Ghoul",
      "Neon Genesis Evangelion",
      "Haikyuu",
      "Chainsaw Man",
      "Mob Psycho 100",
      "JoJo's Bizarre Adventure",
      "Black Clover",
      "Blue Lock",
      "Spy x Family",
      "Vinland Saga",
      "Your Name",
      "Fullmetal Alchemist: Brotherhood",
      "Steins;Gate",
      "Hunter x Hunter (2011)",
      "Witch Hat Atelier",
      "Monster",
      "Frieren: Beyond Journey's End",
      "Sakamoto Days",
      "Gachiakuta",
      "Code Geass",
      "Re:Zero -Starting Life in Another World-",
      "Dan Da Dan",
      "Cyberpunk: Edgerunners",
      "Bocchi the Rock!",
      "Samurai Champloo",
      "Violet Evergarden",
      "Gurren Lagann",
      "Your Lie in April",
      "The Summer Hikaru Died",
      "Mushishi",
      "Kaiju No. 8",
      "Oshi No Ko",
      "Solo Leveling",
      "Parasyte: The Maxim",
      "Made in Abyss",
      "March Comes in Like a Lion",
      "Akane-banashi",
      "Dr. Stone",
      "Hajime no Ippo",
      "Serial Experiments Lain",
      "Great Teacher Onizuka",
      "Kaguya-sama: Love is War",
      "Trigun",
      "Pluto",
      "Dororo",
      "86 Eighty-Six",
      "Berserk",
      "Tatami Galaxy",
      "Nana"
    ]
  },
  {
    "category": "Body & health",
    "words": [
      "heart",
      "lungs",
      "brain",
      "liver",
      "kidney",
      "stomach",
      "muscle",
      "bone",
      "skin",
      "blood pressure",
      "vitamin",
      "vaccine",
      "allergy",
      "migraine",
      "insomnia",
      "yoga",
      "meditation",
      "checkup",
      "physical therapy",
      "first aid",
      "hydration",
      "metabolism",
      "immune system",
      "posture",
      "cardio",
      "balanced diet",
      "mental health",
      "stretching",
      "protein",
      "sleep cycle",
      "cholesterol",
      "body temperature",
      "heart rate",
      "oxygen level",
      "blood sugar",
      "hydration level",
      "muscle recovery",
      "warmup",
      "cooldown",
      "vitamin D",
      "zinc",
      "calcium",
      "iron",
      "electrolytes",
      "mindfulness",
      "wellness plan",
      "doctor visit",
      "respiration",
      "joint mobility",
      "core strength"
    ]
  },
  {
    "category": "School & education",
    "words": [
      "homework",
      "exam",
      "graduation",
      "textbook",
      "whiteboard",
      "backpack",
      "detention",
      "GPA",
      "scholarship",
      "cafeteria",
      "locker",
      "prom",
      "science fair",
      "presentation",
      "study group",
      "tutor",
      "dean",
      "campus",
      "lecture",
      "thesis",
      "semester",
      "attendance",
      "syllabus",
      "report card",
      "recess",
      "group project",
      "lab experiment",
      "field trip",
      "elective",
      "office hours",
      "midterm",
      "valedictorian",
      "final exam",
      "quiz",
      "blackboard",
      "school bus",
      "yearbook",
      "hall pass",
      "principal",
      "transcript",
      "curriculum",
      "math club",
      "debate team",
      "student council",
      "homeroom",
      "credit hours",
      "graduation cap",
      "school bell",
      "semester break",
      "online class"
    ]
  },
  {
    "category": "Hobbies & activities",
    "words": [
      "photography",
      "knitting",
      "gardening",
      "fishing",
      "hiking",
      "camping",
      "painting",
      "pottery",
      "dancing",
      "singing",
      "cooking",
      "baking",
      "origami",
      "birdwatching",
      "collecting cards",
      "woodworking",
      "calligraphy",
      "scrapbooking",
      "rock climbing",
      "board games night",
      "jogging",
      "journaling",
      "chess club",
      "podcasting",
      "video editing",
      "model building",
      "geocaching",
      "home brewing",
      "sewing",
      "beat making",
      "cosplay",
      "stand-up comedy",
      "vlogging",
      "content creation",
      "piano practice",
      "guitar jam",
      "drumming",
      "language learning",
      "puzzle solving",
      "bird feeding",
      "flower arranging",
      "stamp collecting",
      "coin collecting",
      "soap making",
      "candle making",
      "fitness training",
      "callisthenics",
      "blog writing",
      "magic tricks",
      "parkour"
    ]
  },
  {
    "category": "Love & romance",
    "words": [
      "first date",
      "Valentine's",
      "proposal",
      "anniversary",
      "honeymoon",
      "crush",
      "love letter",
      "slow dance",
      "couples trip",
      "matching outfits",
      "candlelit dinner",
      "bouquet",
      "wedding",
      "engagement ring",
      "soulmate",
      "breakup",
      "reconciliation",
      "long distance",
      "double date",
      "promise ring",
      "love song",
      "heartfelt text",
      "picnic date",
      "movie night",
      "handwritten note",
      "meeting the parents",
      "pet names",
      "relationship goals",
      "surprise date",
      "weekend getaway",
      "anniversary gift",
      "matching bracelets",
      "holding hands",
      "first kiss",
      "cute nickname",
      "date night",
      "flowers",
      "romantic playlist",
      "candlelight",
      "proposal speech",
      "engagement party",
      "couple selfie",
      "beach sunset",
      "long hug",
      "love poem",
      "sweet message",
      "couple goals",
      "coffee date",
      "slow walk",
      "stargazing"
    ]
  },
  {
    "category": "Countries",
    "words": [
      "Afghanistan",
      "Albania",
      "Algeria",
      "Andorra",
      "Angola",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bhutan",
      "Bolivia",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Brunei",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Colombia",
      "Comoros",
      "Congo (Republic of the)",
      "Costa Rica",
      "Cote d'Ivoire",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czechia",
      "Democratic Republic of the Congo",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Eswatini",
      "Ethiopia",
      "Fiji",
      "Finland",
      "France",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guatemala",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Honduras",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Micronesia",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "North Korea",
      "North Macedonia",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestine",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russia",
      "Rwanda",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Korea",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "Sudan",
      "Suriname",
      "Sweden",
      "Switzerland",
      "Syria",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Vatican City",
      "Venezuela",
      "Vietnam",
      "Yemen",
      "Zambia",
      "Zimbabwe",
      "Taiwan",
      "Kosovo",
      "Western Sahara",
      "Niue"
    ]
  }
];
