/**
 * Fallback when word-packs.json cannot load (e.g. file://). Mirrors word-packs.json.
 */
window.WORD_PACKS_BUILTIN = [
  {
    "category": "Everyday objects",
    "words": [
      "umbrella",
      "toothbrush",
      "backpack",
      "lamp",
      "mirror",
      "pillow",
      "wallet",
      "headphones",
      "charger",
      "keys",
      "watch",
      "sunglasses",
      "notebook",
      "pen",
      "water bottle",
      "tissue box",
      "remote",
      "blanket",
      "hanger",
      "soap"
    ]
  },
  {
    "category": "Food & drink",
    "words": [
      "pizza",
      "sushi",
      "coffee",
      "popcorn",
      "avocado",
      "croissant",
      "smoothie",
      "noodles",
      "burger",
      "tacos",
      "ice cream",
      "ramen",
      "bagel",
      "matcha",
      "bubble tea",
      "steak",
      "salad",
      "pancakes",
      "hot dog",
      "fries"
    ]
  },
  {
    "category": "Places",
    "words": [
      "library",
      "airport",
      "beach",
      "gym",
      "museum",
      "campground",
      "bakery",
      "theater",
      "zoo",
      "mall",
      "hospital",
      "school",
      "park",
      "restaurant",
      "hotel",
      "subway station",
      "church",
      "stadium",
      "spa",
      "arcade"
    ]
  },
  {
    "category": "Animals",
    "words": [
      "penguin",
      "octopus",
      "flamingo",
      "raccoon",
      "hedgehog",
      "dolphin",
      "sloth",
      "owl",
      "elephant",
      "tiger",
      "giraffe",
      "koala",
      "panda",
      "wolf",
      "fox",
      "eagle",
      "shark",
      "turtle",
      "rabbit",
      "horse"
    ]
  },
  {
    "category": "Christmas",
    "words": [
      "Santa",
      "reindeer",
      "snowman",
      "ornament",
      "wreath",
      "mistletoe",
      "gingerbread",
      "eggnog",
      "stocking",
      "elf",
      "sleigh",
      "carol",
      "nutcracker",
      "candy cane",
      "fireplace",
      "advent calendar",
      "tinsel",
      "holly",
      "North Pole",
      "gift wrap"
    ]
  },
  {
    "category": "Objects",
    "words": [
      "hammer",
      "scissors",
      "tape",
      "glue",
      "stapler",
      "calendar",
      "alarm clock",
      "umbrella stand",
      "vacuum",
      "broom",
      "flashlight",
      "battery",
      "extension cord",
      "picture frame",
      "vase",
      "candle",
      "clock",
      "rug",
      "curtain",
      "bookshelf"
    ]
  },
  {
    "category": "Movie titles",
    "words": [
      "Titanic",
      "Avatar",
      "Barbie",
      "Oppenheimer",
      "Frozen",
      "The Lion King",
      "Star Wars",
      "Harry Potter",
      "The Godfather",
      "Jurassic Park",
      "The Dark Knight",
      "Inception",
      "Forrest Gump",
      "Shrek",
      "Toy Story",
      "Finding Nemo",
      "Black Panther",
      "Spider-Man",
      "The Matrix",
      "La La Land",
      "Get Out",
      "Top Gun",
      "Rocky",
      "E.T.",
      "Jaws",
      "Casablanca",
      "Gladiator",
      "Minions",
      "The Avengers",
      "Lord of the Rings"
    ]
  },
  {
    "category": "Music",
    "words": [
      "The Beatles",
      "Frank Sinatra",
      "Elvis Presley",
      "Michael Jackson",
      "Madonna",
      "Queen",
      "David Bowie",
      "Prince",
      "Whitney Houston",
      "Stevie Wonder",
      "Elton John",
      "Taylor Swift",
      "Drake",
      "Kanye West",
      "Beyoncé",
      "Rihanna",
      "Ariana Grande",
      "Billie Eilish",
      "The Weeknd",
      "Travis Scott",
      "Kendrick Lamar",
      "Eminem",
      "Jay-Z",
      "Bad Bunny",
      "Central Cee",
      "Polo G",
      "SZA",
      "Doja Cat",
      "Harry Styles",
      "Olivia Rodrigo",
      "BTS",
      "BLACKPINK",
      "Nirvana",
      "Metallica",
      "AC/DC",
      "Coldplay",
      "Radiohead",
      "Adele",
      "Ed Sheeran",
      "Celine Dion"
    ]
  },
  {
    "category": "Locations",
    "words": [
      "Times Square",
      "Eiffel Tower",
      "Grand Canyon",
      "Big Ben",
      "Great Wall",
      "Machu Picchu",
      "Sydney Opera House",
      "Niagara Falls",
      "Hollywood",
      "Central Park",
      "Stonehenge",
      "Colosseum",
      "Taj Mahal",
      "Mount Everest",
      "Sahara Desert",
      "Amazon Rainforest",
      "Venice canals",
      "Las Vegas Strip",
      "Golden Gate Bridge",
      "Statue of Liberty"
    ]
  },
  {
    "category": "Sports",
    "words": [
      "basketball",
      "soccer",
      "tennis",
      "baseball",
      "football",
      "volleyball",
      "golf",
      "swimming",
      "boxing",
      "skiing",
      "surfing",
      "hockey",
      "cricket",
      "rugby",
      "badminton",
      "wrestling",
      "cycling",
      "marathon",
      "skateboarding",
      "gymnastics"
    ]
  },
  {
    "category": "Professions",
    "words": [
      "doctor",
      "nurse",
      "teacher",
      "engineer",
      "lawyer",
      "chef",
      "pilot",
      "firefighter",
      "police officer",
      "scientist",
      "artist",
      "musician",
      "writer",
      "architect",
      "dentist",
      "veterinarian",
      "electrician",
      "plumber",
      "journalist",
      "accountant"
    ]
  },
  {
    "category": "Brands",
    "words": [
      "Nike",
      "Apple",
      "Google",
      "Amazon",
      "Starbucks",
      "McDonald's",
      "Coca-Cola",
      "Disney",
      "Samsung",
      "Sony",
      "Adidas",
      "IKEA",
      "Netflix",
      "Spotify",
      "Lego",
      "Toyota",
      "BMW",
      "Gucci",
      "Prada",
      "Nintendo"
    ]
  },
  {
    "category": "Tools",
    "words": [
      "screwdriver",
      "wrench",
      "pliers",
      "drill",
      "saw",
      "measuring tape",
      "level",
      "chisel",
      "sandpaper",
      "ladder",
      "wheelbarrow",
      "shovel",
      "rake",
      "pickaxe",
      "clamp",
      "file",
      "hex key",
      "socket",
      "mallet",
      "multimeter"
    ]
  },
  {
    "category": "Vehicles",
    "words": [
      "bicycle",
      "motorcycle",
      "scooter",
      "suv",
      "pickup truck",
      "convertible",
      "ambulance",
      "fire truck",
      "tractor",
      "bulldozer",
      "forklift",
      "subway",
      "helicopter",
      "speedboat",
      "cruise ship",
      "jet ski",
      "skateboard",
      "roller skates",
      "golf cart",
      "camper van"
    ]
  },
  {
    "category": "Superpowers",
    "words": [
      "flight",
      "invisibility",
      "teleportation",
      "super strength",
      "mind reading",
      "time travel",
      "laser eyes",
      "healing",
      "shape-shifting",
      "telekinesis",
      "super speed",
      "force field",
      "weather control",
      "duplication",
      "talking to animals",
      "phasing through walls",
      "elastic body",
      "ice powers",
      "fire powers",
      "electricity powers"
    ]
  },
  {
    "category": "Fears",
    "words": [
      "heights",
      "spiders",
      "snakes",
      "public speaking",
      "darkness",
      "thunder",
      "needles",
      "flying",
      "deep water",
      "tight spaces",
      "clowns",
      "dentist",
      "ghosts",
      "failure",
      "rejection",
      "loneliness",
      "crowds",
      "germs",
      "dogs",
      "bees"
    ]
  },
  {
    "category": "Inventions",
    "words": [
      "light bulb",
      "telephone",
      "airplane",
      "internet",
      "printing press",
      "camera",
      "refrigerator",
      "microwave",
      "GPS",
      "antibiotics",
      "vaccine",
      "steam engine",
      "wheel",
      "compass",
      "gunpowder",
      "paper",
      "glasses",
      "battery",
      "semiconductor",
      "3D printer"
    ]
  },
  {
    "category": "Celebrities",
    "words": [
      "Tom Hanks",
      "Dwayne Johnson",
      "Jennifer Lawrence",
      "Leonardo DiCaprio",
      "Zendaya",
      "Will Smith",
      "Meryl Streep",
      "Robert Downey Jr.",
      "Margot Robbie",
      "Ryan Reynolds",
      "Emma Stone",
      "Chris Hemsworth",
      "Scarlett Johansson",
      "Keanu Reeves",
      "Timothée Chalamet",
      "Lady Gaga",
      "Denzel Washington",
      "Sandra Bullock",
      "Jackie Chan",
      "Morgan Freeman"
    ]
  },
  {
    "category": "Games",
    "words": [
      "Monopoly",
      "Chess",
      "Uno",
      "Scrabble",
      "Clue",
      "Risk",
      "Jenga",
      "Poker",
      "Minecraft",
      "Fortnite",
      "Mario Kart",
      "The Sims",
      "Among Us",
      "Roblox",
      "Call of Duty",
      "FIFA",
      "Pokémon",
      "Zelda",
      "Halo",
      "Grand Theft Auto"
    ]
  },
  {
    "category": "Anime",
    "words": [
      "Naruto",
      "Dragon Ball",
      "One Piece",
      "Attack on Titan",
      "Demon Slayer",
      "My Hero Academia",
      "Death Note",
      "Fullmetal Alchemist",
      "Sailor Moon",
      "Spirited Away",
      "Cowboy Bebop",
      "Jujutsu Kaisen",
      "Hunter x Hunter",
      "Bleach",
      "Studio Ghibli",
      "Pokémon anime",
      "One Punch Man",
      "Tokyo Ghoul",
      "Neon Genesis Evangelion",
      "Haikyuu"
    ]
  },
  {
    "category": "Body & health",
    "words": [
      "heart",
      "lungs",
      "brain",
      "liver",
      "kidney",
      "stomach",
      "muscle",
      "bone",
      "skin",
      "blood pressure",
      "vitamin",
      "vaccine",
      "allergy",
      "migraine",
      "insomnia",
      "yoga",
      "meditation",
      "checkup",
      "physical therapy",
      "first aid"
    ]
  },
  {
    "category": "School & education",
    "words": [
      "homework",
      "exam",
      "graduation",
      "textbook",
      "whiteboard",
      "backpack",
      "detention",
      "GPA",
      "scholarship",
      "cafeteria",
      "locker",
      "prom",
      "science fair",
      "presentation",
      "study group",
      "tutor",
      "dean",
      "campus",
      "lecture",
      "thesis"
    ]
  },
  {
    "category": "Hobbies & activities",
    "words": [
      "photography",
      "knitting",
      "gardening",
      "fishing",
      "hiking",
      "camping",
      "painting",
      "pottery",
      "dancing",
      "singing",
      "cooking",
      "baking",
      "origami",
      "birdwatching",
      "collecting cards",
      "woodworking",
      "calligraphy",
      "scrapbooking",
      "rock climbing",
      "board games night"
    ]
  },
  {
    "category": "Love & romance",
    "words": [
      "first date",
      "Valentine's",
      "proposal",
      "anniversary",
      "honeymoon",
      "crush",
      "love letter",
      "slow dance",
      "couples trip",
      "matching outfits",
      "candlelit dinner",
      "bouquet",
      "wedding",
      "engagement ring",
      "soulmate",
      "breakup",
      "reconciliation",
      "long distance",
      "double date",
      "promise ring"
    ]
  },
  {
    "category": "Countries",
    "words": [
      "United States",
      "Canada",
      "Mexico",
      "Brazil",
      "United Kingdom",
      "France",
      "Germany",
      "Italy",
      "Spain",
      "Japan",
      "China",
      "India",
      "Australia",
      "Egypt",
      "South Africa",
      "Nigeria",
      "South Korea",
      "Thailand",
      "Argentina",
      "Sweden"
    ]
  },
  {
    "category": "Cities",
    "words": [
      "New York",
      "Los Angeles",
      "London",
      "Paris",
      "Tokyo",
      "Dubai",
      "Singapore",
      "Berlin",
      "Mumbai",
      "Sydney",
      "Toronto",
      "Chicago",
      "Seoul",
      "Barcelona",
      "Amsterdam",
      "Mexico City",
      "Cairo",
      "Lagos",
      "Rio de Janeiro",
      "Vancouver"
    ]
  }
];
